stages:
 - test
 - build

tests:
  stage: test
  tags:
   - python
  script:
   - nose2-3

build_wheel:
 stage: build
 tags:
  - python
 only:
  - master
 script:
  python3 setup.py bdist_wheel
 artifacts:
  paths:
   - dists/*

build_deb:
 stage: build
 tags:
  - python
 only:
  - master
 script:
  fakeroot dpkg-buildpackage -us -uc
  mkdir dists
  mv ../python3-unitd*.deb ../webrun*.deb dists/
 artifacts:
  paths:
   - dists/*
