#!/usr/bin/python3

import asyncio
import argparse
import logging
import signal
import os
import sys

DEFAULT_GEOMETRY = "1000x750"

log = logging.getLogger()

class Runner:
    def __init__(self, args):
        self.args = args
        self.display_number = 100 # TODO: generate a unique display number
        self.loop = asyncio.get_event_loop()

    @asyncio.coroutine
    def start_xserver(self):
        # When starting an X server, if the X server sees that SIGUSR1 is
        # ignored, it sends SIGUSR1 to the parent process when it is ready to
        # accept connections. We wait until we receive SIGUSR1 before declaring
        # that the X server has been started.

        server_ready = self.loop.create_future()
        def _on_sigusr1():
            self.loop.remove_signal_handler(signal.SIGUSR1)
            server_ready.set_result(True)
        self.loop.add_signal_handler(signal.SIGUSR1, _on_sigusr1)

        def _before_xserver():
            signal.signal(signal.SIGUSR1, signal.SIG_IGN)
        self.xserver = yield from asyncio.create_subprocess_exec(
                "Xtigervnc",
                "-geometry", self.args.geometry,
                "-desktop", self.args.title,
                "-SecurityTypes", "None",
                "-localhost",
                ":{}".format(self.display_number),
                preexec_fn=_before_xserver,
        )

        yield from server_ready


    @asyncio.coroutine
    def start_xclient(self):
        env = dict(os.environ)
        env["DISPLAY"] = ":{}".format(self.display_number)
        self.xclient = yield from asyncio.create_subprocess_exec(
                *self.args.cmd,
                env=env,
        )

    @asyncio.coroutine
    def start(self):
        log.info("Starting X server")
        yield from self.start_xserver()

        log.info("Starting X client")
        yield from self.start_xclient()

        log.info("Ready for connections")
        yield from asyncio.sleep(3)

        log.info("Terminating")
        self.xclient.terminate()
        self.xserver.terminate()

        log.info("Waiting")
        yield from self.xclient.wait()
        yield from self.xserver.wait()



def main():
    parser = argparse.ArgumentParser(
            description="start X client on a private X server exported via VNC on the web",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--verbose", "-v", action="store_true", help="verbose output")
    parser.add_argument("--debug", action="store_true", help="debug output")
    parser.add_argument("--geometry", action="store", default=DEFAULT_GEOMETRY, help="X display geometry")
    parser.add_argument("--title", action="store", default="Desktop session", help="desktop session title")
    parser.add_argument("cmd", nargs="+", help="command and arguments to run")

    args = parser.parse_args()

    log_format = "%(asctime)-15s %(levelname)s %(message)s"
    level = logging.WARN
    if args.debug:
        level = logging.DEBUG
    elif args.verbose:
        level = logging.INFO
    logging.basicConfig(level=level, stream=sys.stderr, format=log_format)

    runner = Runner(args)

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(runner.start())
    finally:
        loop.close()


if __name__ == "__main__":
    main()
